name: plan_q
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  dio_smart_retry: ^7.0.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  pinput: ^5.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  lottie: ^3.3.1
  flutter_image_compress: ^2.4.0
  wechat_camera_picker: ^4.3.7
  share_plus: ^10.1.4
  pod_player: ^0.2.2
  dropdown_flutter: ^1.0.1
  google_nav_bar: ^5.0.7
  time_range: ^1.1.1
  percent_indicator: ^4.2.5
  table_calendar: ^3.2.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  rename: ^3.0.2
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_gen: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lora
      fonts:
        # - asset: assets/fonts/OpenSans-Bold.ttf
        # - asset: assets/fonts/OpenSans-ExtraBold.ttf
        # - asset: assets/fonts/OpenSans-Light.ttf
        # - asset: assets/fonts/OpenSans-Medium.ttf
        # - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora-Italic.ttf
        - asset: assets/fonts/Lora-Medium.ttf
        - asset: assets/fonts/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf